name: Jekyll site CI

on:
  push:
    branches:
    - master
  repository_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Use up to date submodules
      uses: srt32/git-actions@v0.0.3
      with:
        args: git submodule update --init --remote --merge
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./
