name: Jekyll site CI

on:
  push:
    branches:
    - master
  repository_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Use up to date submodules
      uses: srt32/git-actions@v0.0.3
      with:
        args: git submodule update --init --remote --merge
    - name: Install SSH Client 🔑
      uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
  
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        SSH: true
        BRANCH: gh-pages
        FOLDER: .
